#!/bin/bash

set -x

if [ ! -d $OPENSHIFT_DATA_DIR/m2/repository ]
        then
                cd $OPENSHIFT_DATA_DIR
				mkdir m2/repository                
fi

if [ ! -d $OPENSHIFT_DATA_DIR/logs ]
        then
                cd $OPENSHIFT_DATA_DIR
				mkdir logs
fi

if [ ! -d $OPENSHIFT_DATA_DIR/jdk8 ]
        then
                cd $OPENSHIFT_DATA_DIR
                wget --no-check-certificate --no-cookies --header "Cookie: oraclelicense=accept-securebackup-cookie" http://download.oracle.com/otn-pub/java/jdk/8u60-b27/jdk-8u60-linux-x64.tar.gz
                tar xvf *.tar.gz
                rm -f *.tar.gz
                mv jdk-8u60-linux-x64 jdk8
fi

if [ ! -d $OPENSHIFT_DATA_DIR/maven ]
        then
                cd $OPENSHIFT_DATA_DIR
                wget http://mirror.cc.columbia.edu/pub/software/apache/maven/maven-3/3.3.3/binaries/apache-maven-3.3.3-bin.tar.gz
                tar xvf *.tar.gz
                rm -f *.tar.gz
                mv apache-maven-3.3.3 maven
fi


cd $OPENSHIFT_REPO_DIR
export MAVEN_BIN=maven/bin
export M2=$OPENSHIFT_DATA_DIR$MAVEN_BIN
export MAVEN_OPTS="-Xms384m -Xmx412m"
export JAVA_BIN=jdk8/bin
export JDK=$OPENSHIFT_DATA_DIR$JAVA_BIN
export PATH=$JDK:$M2:$PATH

mvn -s settings.xml clean install